server:
  port: 8701
  
spring:
  application:
    name: eureka-server 
  # Security
  security:
    user:
      name: admin
      password: 123
      
# Eureka
eureka:
  instance:
    hostname: localhost
  # Standalone Mode
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  #  Cluster Mode
#  client: 
#    serviceUrl: 
#      defaultZone: http://admin:123@host2:8702/eureka/,http://admin:123@host3:8703/eureka/
  datacenter: cloud
  environment: prod
  # USED ONLY IN DEVELOPMENT MODE
  # DevMode: Remove invalidate Eureka server
#  server: 
#    enableSelfPreservation: false
#    evictionIntervalTimerInMs: 4000

    
