server:
  port: 6001
  
spring:
  application:
    name: config-server
  # Native
  profiles:
    active: native
  cloud:
    config:
      server:
        # Native Config
        native:
          searchLocations: classpath:/config/{application}/
    stream:
      # e.g., 'kafka', 'rabbit'
      default-binder: kafka
  # Security
  security:
    user:
      name: admin
      password: 123      
  # Spring Cloud Bus
#  rabbitmq:
#    host: localhost
#    password: 123
#    port: 5672
#    username: admin
  kafka: 
    bootstrap-servers:
     - localhost:9092
      
# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123@localhost:8701/eureka
#      defaultZone: http://admin:123@host1:8701/eureka/,http://admin:123@host2:8702/eureka/,http://admin:123@host3:8703/eureka/
        
# Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
      